# networks:
#   lsu: {}

# services:
#   landing:
#     container_name: lsu_landing
#     labels:
#       - "traefik.enable=true"
#       - "traefik.http.routers.landing.rule=Host(`landing.example.com`)"
#       - "traefik.http.routers.landing.entrypoints=web"
#     networks:
#       - lsu

#   reverse-proxy:
#     image: traefik:v3.2.1
#     command:
#       - "--api.insecure=true"
#       - "--providers.docker=true"
#       - "--providers.docker.exposedbydefault=false"
#       - "--entrypoints.web.address=:80"
#       - "--entrypoints.websecure.address=:443"
#     ports:
#       - "80:80"
#       - "443:443"
#     volumes:
#       - "/var/run/docker.sock:/var/run/docker.sock:ro"
#       - "./certs:/certs"
#     networks:
#       - lsu

#   certbot:
#     image: certbot/certbot
#     container_name: certbot
#     volumes:
#       - "./certs:/etc/letsencrypt"
#       - "./www:/var/www/html"
#     entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 2073600; done'"
#     networks:
#       # - lsu

networks:
  lsu: {}

services:
  landing:
    container_name: lsu_landing
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.landing.rule=Host(`landing.example.com`)"
      - "traefik.http.routers.landing.entrypoints=websecure"
      - "traefik.http.routers.landing.tls=true"
      - "traefik.http.routers.landing.tls.certresolver=myresolver"
    networks:
      - lsu
    ports:
      - "8005:8005"

  reverse-proxy:
    image: traefik:v3.2.1
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=your-email@example.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "letsencrypt:/letsencrypt"
    networks:
      - lsu

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - "letsencrypt:/etc/letsencrypt"
      - "www:/var/www/html"
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 2073600; done'"
    networks:
      - lsu

volumes:
  letsencrypt:
  www: