# Image de base Node.js pour le développement
FROM node:22-alpine

# Installation des dépendances système nécessaires
RUN apk add --no-cache libc6-compat

# Définition du répertoire de travail
WORKDIR /app

# Copie des fichiers de dépendances
COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* .npmrc* ./

# Installation des dépendances selon le gestionnaire de paquets utilisé
RUN \
    if [ -f yarn.lock ]; then yarn install; \
    elif [ -f package-lock.json ]; then npm install; \
    elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm install; \
    else echo "Lockfile not found." && exit 1; \
    fi

# Copie du reste des fichiers du projet
COPY . .

# Exposition du port de développement
EXPOSE 3000

# Configuration des variables d'environnement
ENV NODE_ENV=development
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

# Commande pour démarrer le serveur de développement
CMD \
    if [ -f yarn.lock ]; then yarn dev; \
    elif [ -f package-lock.json ]; then npm run dev; \
    elif [ -f pnpm-lock.yaml ]; then pnpm dev; \
    else echo "Lockfile not found." && exit 1; \
    fi 